//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR7.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LR7.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainWindow_Menu_Edit {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Highlighting.
        /// </summary>
        public static string MainWindow_Menu_Edit_SyntaxHighlighting {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Edit.SyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string MainWindow_Menu_Edit_SyntaxHighlighting_Off {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Edit.SyntaxHighlighting.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string MainWindow_Menu_Edit_SyntaxHighlighting_On {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Edit.SyntaxHighlighting.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_Menu_File {
            get {
                return ResourceManager.GetString("MainWindow.Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainWindow_Menu_File_Open {
            get {
                return ResourceManager.GetString("MainWindow.Menu.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTF File.
        /// </summary>
        public static string MainWindow_Menu_File_Open_Rtf {
            get {
                return ResourceManager.GetString("MainWindow.Menu.File.Open.Rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT File.
        /// </summary>
        public static string MainWindow_Menu_File_Open_Txt {
            get {
                return ResourceManager.GetString("MainWindow.Menu.File.Open.Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_Menu_File_Save {
            get {
                return ResourceManager.GetString("MainWindow.Menu.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format (RTF).
        /// </summary>
        public static string MainWindow_Menu_File_Save_Rtf {
            get {
                return ResourceManager.GetString("MainWindow.Menu.File.Save.Rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (TXT).
        /// </summary>
        public static string MainWindow_Menu_File_Save_Txt {
            get {
                return ResourceManager.GetString("MainWindow.Menu.File.Save.Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MainWindow_Menu_Language {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MainWindow_Menu_Language_English {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Language.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string MainWindow_Menu_Language_Ukrainian {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Language.Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string MainWindow_Menu_Theme {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string MainWindow_Menu_Theme_Dark {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string MainWindow_Menu_Theme_Light {
            get {
                return ResourceManager.GetString("MainWindow.Menu.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters:.
        /// </summary>
        public static string MainWindow_Status_Letters {
            get {
                return ResourceManager.GetString("MainWindow.Status.Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words: .
        /// </summary>
        public static string MainWindow_Status_Words {
            get {
                return ResourceManager.GetString("MainWindow.Status.Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaganary Studio: Code.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
    }
}
